Implement-tear-offs
SpinlockLabs/github.dart pull request #345
Opened 2022-12-15 02:43 UTC by tyler-jewell

chore: Implemented tear-offs where recommended by Dart for cleaner code
test: created tests for authorizations_services. More to come in future.

2023-01-26 21:13 UTC, CaseyHillers approved these changes
LGTM! Can you update the changelog and pubspec as well?

2023-07-05 23:02 UTC, kevmoo requested changes

2023-07-05 23:02 UTC, kevmoo commented on lib/src/common/util/pagination.dart
> +      log(response.body);
```suggestion
```

Should remove this!

2023-07-05 23:02 UTC, kevmoo commented on pubspec.yaml
> +  mocktail: ^0.3.0
Do we get "enough" from this new package to add it as a dependency?

2024-03-24 18:39 UTC, closed without merging